# Generated by Django 5.2 on 2025-11-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("about", models.TextField()),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="management_pics/"
                    ),
                ),
            ],
        ),
    ]
