# Generated by Django 5.2 on 2025-11-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0002_managementprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="managementprofile",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
