# Generated by Django 5.2 on 2025-11-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0003_managementprofile_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="managementprofile",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
