# Generated by Django 5.2 on 2025-12-05 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0005_managementprofile_uploaded_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="section",
            field=models.CharField(
                choices=[
                    ("first", "First Section"),
                    ("second", "Second Section"),
                    ("third", "Third Section"),
                ],
                default="first",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
