# Generated by Django 5.2 on 2025-12-07 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0006_galleryimage_section_alter_galleryimage_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galleryimage",
            options={"ordering": ["created_at"]},
        ),
    ]
