# Generated by Django 5.2 on 2025-12-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0007_alter_galleryimage_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("job_type", models.CharField(max_length=100)),
                ("duties", models.TextField()),
                ("apply_note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
